package com.riskvis.entity;

// Generated May 12, 2014 11:45:38 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InsurancesHasPlacesrisksId generated by hbm2java
 */
@Embeddable
public class InsurancesHasPlacesrisksId extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = -3820476737233534341L;
	private int insurancesIdinsurances;
	private int placesrisksIdrisks;

	public InsurancesHasPlacesrisksId() {
	}

	public InsurancesHasPlacesrisksId(int insurancesIdinsurances,
			int placesrisksIdrisks) {
		this.insurancesIdinsurances = insurancesIdinsurances;
		this.placesrisksIdrisks = placesrisksIdrisks;
	}

	@Column(name = "insurances_idinsurances", nullable = false)
	public int getInsurancesIdinsurances() {
		return this.insurancesIdinsurances;
	}

	public void setInsurancesIdinsurances(int insurancesIdinsurances) {
		this.insurancesIdinsurances = insurancesIdinsurances;
	}

	@Column(name = "placesrisks_idrisks", nullable = false)
	public int getPlacesrisksIdrisks() {
		return this.placesrisksIdrisks;
	}

	public void setPlacesrisksIdrisks(int placesrisksIdrisks) {
		this.placesrisksIdrisks = placesrisksIdrisks;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InsurancesHasPlacesrisksId))
			return false;
		InsurancesHasPlacesrisksId castOther = (InsurancesHasPlacesrisksId) other;

		return (this.getInsurancesIdinsurances() == castOther
				.getInsurancesIdinsurances())
				&& (this.getPlacesrisksIdrisks() == castOther
						.getPlacesrisksIdrisks());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInsurancesIdinsurances();
		result = 37 * result + this.getPlacesrisksIdrisks();
		return result;
	}

}
