package com.riskvis.entity;

// Generated May 12, 2014 11:45:38 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InsurancesHasTransportationrisksId generated by hbm2java
 */
@Embeddable
public class InsurancesHasTransportationrisksId extends AbstractEntity
		implements java.io.Serializable {

	private static final long serialVersionUID = 853012830257816087L;
	private int insurancesIdinsurances;
	private int risksIdrisks;

	public InsurancesHasTransportationrisksId() {
	}

	public InsurancesHasTransportationrisksId(int insurancesIdinsurances,
			int risksIdrisks) {
		this.insurancesIdinsurances = insurancesIdinsurances;
		this.risksIdrisks = risksIdrisks;
	}

	@Column(name = "insurances_idinsurances", nullable = false)
	public int getInsurancesIdinsurances() {
		return this.insurancesIdinsurances;
	}

	public void setInsurancesIdinsurances(int insurancesIdinsurances) {
		this.insurancesIdinsurances = insurancesIdinsurances;
	}

	@Column(name = "risks_idrisks", nullable = false)
	public int getRisksIdrisks() {
		return this.risksIdrisks;
	}

	public void setRisksIdrisks(int risksIdrisks) {
		this.risksIdrisks = risksIdrisks;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InsurancesHasTransportationrisksId))
			return false;
		InsurancesHasTransportationrisksId castOther = (InsurancesHasTransportationrisksId) other;

		return (this.getInsurancesIdinsurances() == castOther
				.getInsurancesIdinsurances())
				&& (this.getRisksIdrisks() == castOther.getRisksIdrisks());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInsurancesIdinsurances();
		result = 37 * result + this.getRisksIdrisks();
		return result;
	}

}
