package com.riskvis.entity;

// Generated May 12, 2014 11:45:38 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlayersHasQuestsId generated by hbm2java
 */
@Embeddable
public class PlayersHasQuestsId extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = -5781069262331578685L;
	private int playersIdplayers;
	private int questsIdquests;

	public PlayersHasQuestsId() {
	}

	public PlayersHasQuestsId(int playersIdplayers, int questsIdquests) {
		this.playersIdplayers = playersIdplayers;
		this.questsIdquests = questsIdquests;
	}

	@Column(name = "players_idplayers", nullable = false)
	public int getPlayersIdplayers() {
		return this.playersIdplayers;
	}

	public void setPlayersIdplayers(int playersIdplayers) {
		this.playersIdplayers = playersIdplayers;
	}

	@Column(name = "quests_idquests", nullable = false)
	public int getQuestsIdquests() {
		return this.questsIdquests;
	}

	public void setQuestsIdquests(int questsIdquests) {
		this.questsIdquests = questsIdquests;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlayersHasQuestsId))
			return false;
		PlayersHasQuestsId castOther = (PlayersHasQuestsId) other;

		return (this.getPlayersIdplayers() == castOther.getPlayersIdplayers())
				&& (this.getQuestsIdquests() == castOther.getQuestsIdquests());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlayersIdplayers();
		result = 37 * result + this.getQuestsIdquests();
		return result;
	}

}
