package com.riskvis.entity;

// Generated Sep 29, 2014 10:02:36 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlayersHasInsurances generated by hbm2java
 */
@Deprecated
@Entity
@Table(name = "players_has_insurances", catalog = "test")
public class PlayersHasInsurances extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = -8675489838215845911L;
	private PlayersHasInsurancesId id;
	private Players players;
	private Insurances insurances;

	public PlayersHasInsurances() {
	}

	public PlayersHasInsurances(PlayersHasInsurancesId id, Players players,
			Insurances insurances) {
		this.id = id;
		this.players = players;
		this.insurances = insurances;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "playersIdplayers", column = @Column(name = "players_idplayers", nullable = false)),
			@AttributeOverride(name = "insurancesIdinsurances", column = @Column(name = "insurances_idinsurances", nullable = false)) })
	public PlayersHasInsurancesId getId() {
		return this.id;
	}

	public void setId(PlayersHasInsurancesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "players_idplayers", nullable = false, insertable = false, updatable = false)
	public Players getPlayers() {
		return this.players;
	}

	public void setPlayers(Players players) {
		this.players = players;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "insurances_idinsurances", nullable = false, insertable = false, updatable = false)
	public Insurances getInsurances() {
		return this.insurances;
	}

	public void setInsurances(Insurances insurances) {
		this.insurances = insurances;
	}

}
