package com.riskvis.entity;

// Generated Sep 29, 2014 10:02:36 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestInsurances generated by hbm2java
 */
@Entity
@Table(name = "quest_insurances", catalog = "test")
public class QuestInsurances extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = -8170908385927047533L;
	private QuestInsurancesId id;
	private PlayersHasQuests playersHasQuests;
	private Insurances insurances;

	public QuestInsurances() {
	}

	public QuestInsurances(QuestInsurancesId id,
			PlayersHasQuests playersHasQuests, Insurances insurances) {
		this.id = id;
		this.playersHasQuests = playersHasQuests;
		this.insurances = insurances;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "playersHasQuestsPlayersIdplayers", column = @Column(name = "players_has_quests_players_idplayers", nullable = false)),
			@AttributeOverride(name = "playersHasQuestsQuestsIdquests", column = @Column(name = "players_has_quests_quests_idquests", nullable = false)),
			@AttributeOverride(name = "insurancesIdinsurances", column = @Column(name = "insurances_idinsurances", nullable = false)) })
	public QuestInsurancesId getId() {
		return this.id;
	}

	public void setId(QuestInsurancesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "players_has_quests_players_idplayers", referencedColumnName = "players_idplayers", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "players_has_quests_quests_idquests", referencedColumnName = "quests_idquests", nullable = false, insertable = false, updatable = false) })
	public PlayersHasQuests getPlayersHasQuests() {
		return this.playersHasQuests;
	}

	public void setPlayersHasQuests(PlayersHasQuests playersHasQuests) {
		this.playersHasQuests = playersHasQuests;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "insurances_idinsurances", nullable = false, insertable = false, updatable = false)
	public Insurances getInsurances() {
		return this.insurances;
	}

	public void setInsurances(Insurances insurances) {
		this.insurances = insurances;
	}

}
