package com.riskvis.entity;

// Generated Sep 29, 2014 10:02:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuestInsurancesId generated by hbm2java
 */
@Embeddable
public class QuestInsurancesId extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = -6424774558670500432L;
	private int playersHasQuestsPlayersIdplayers;
	private int playersHasQuestsQuestsIdquests;
	private int insurancesIdinsurances;

	public QuestInsurancesId() {
	}

	public QuestInsurancesId(int playersHasQuestsPlayersIdplayers,
			int playersHasQuestsQuestsIdquests, int insurancesIdinsurances) {
		this.playersHasQuestsPlayersIdplayers = playersHasQuestsPlayersIdplayers;
		this.playersHasQuestsQuestsIdquests = playersHasQuestsQuestsIdquests;
		this.insurancesIdinsurances = insurancesIdinsurances;
	}

	@Column(name = "players_has_quests_players_idplayers", nullable = false)
	public int getPlayersHasQuestsPlayersIdplayers() {
		return this.playersHasQuestsPlayersIdplayers;
	}

	public void setPlayersHasQuestsPlayersIdplayers(
			int playersHasQuestsPlayersIdplayers) {
		this.playersHasQuestsPlayersIdplayers = playersHasQuestsPlayersIdplayers;
	}

	@Column(name = "players_has_quests_quests_idquests", nullable = false)
	public int getPlayersHasQuestsQuestsIdquests() {
		return this.playersHasQuestsQuestsIdquests;
	}

	public void setPlayersHasQuestsQuestsIdquests(
			int playersHasQuestsQuestsIdquests) {
		this.playersHasQuestsQuestsIdquests = playersHasQuestsQuestsIdquests;
	}

	@Column(name = "insurances_idinsurances", nullable = false)
	public int getInsurancesIdinsurances() {
		return this.insurancesIdinsurances;
	}

	public void setInsurancesIdinsurances(int insurancesIdinsurances) {
		this.insurancesIdinsurances = insurancesIdinsurances;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuestInsurancesId))
			return false;
		QuestInsurancesId castOther = (QuestInsurancesId) other;

		return (this.getPlayersHasQuestsPlayersIdplayers() == castOther
				.getPlayersHasQuestsPlayersIdplayers())
				&& (this.getPlayersHasQuestsQuestsIdquests() == castOther
						.getPlayersHasQuestsQuestsIdquests())
				&& (this.getInsurancesIdinsurances() == castOther
						.getInsurancesIdinsurances());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlayersHasQuestsPlayersIdplayers();
		result = 37 * result + this.getPlayersHasQuestsQuestsIdquests();
		result = 37 * result + this.getInsurancesIdinsurances();
		return result;
	}

}
