package com.riskvis.entity;

// Generated Sep 29, 2014 10:02:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TurnsHistoryHasPlacesrisksId generated by hbm2java
 */
@Embeddable
public class TurnsHistoryHasPlacesrisksId extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = -7584880613724276162L;
	private int turnsHistoryPlayersHasQuestsPlayersIdplayers;
	private int turnsHistoryPlayersHasQuestsQuestsIdquests;
	private int turnsHistoryPlacesHasTransportsPlacesOrigin;
	private int turnsHistoryPlacesHasTransportsTransportation;
	private int turnsHistoryPlacesHasTransportsPlacesDestination;
	private int placesrisksIdrisks;

	public TurnsHistoryHasPlacesrisksId() {
	}

	public TurnsHistoryHasPlacesrisksId(
			int turnsHistoryPlayersHasQuestsPlayersIdplayers,
			int turnsHistoryPlayersHasQuestsQuestsIdquests,
			int turnsHistoryPlacesHasTransportsPlacesOrigin,
			int turnsHistoryPlacesHasTransportsTransportation,
			int turnsHistoryPlacesHasTransportsPlacesDestination,
			int placesrisksIdrisks) {
		this.turnsHistoryPlayersHasQuestsPlayersIdplayers = turnsHistoryPlayersHasQuestsPlayersIdplayers;
		this.turnsHistoryPlayersHasQuestsQuestsIdquests = turnsHistoryPlayersHasQuestsQuestsIdquests;
		this.turnsHistoryPlacesHasTransportsPlacesOrigin = turnsHistoryPlacesHasTransportsPlacesOrigin;
		this.turnsHistoryPlacesHasTransportsTransportation = turnsHistoryPlacesHasTransportsTransportation;
		this.turnsHistoryPlacesHasTransportsPlacesDestination = turnsHistoryPlacesHasTransportsPlacesDestination;
		this.placesrisksIdrisks = placesrisksIdrisks;
	}

	@Column(name = "turns_history_players_has_quests_players_idplayers", nullable = false)
	public int getTurnsHistoryPlayersHasQuestsPlayersIdplayers() {
		return this.turnsHistoryPlayersHasQuestsPlayersIdplayers;
	}

	public void setTurnsHistoryPlayersHasQuestsPlayersIdplayers(
			int turnsHistoryPlayersHasQuestsPlayersIdplayers) {
		this.turnsHistoryPlayersHasQuestsPlayersIdplayers = turnsHistoryPlayersHasQuestsPlayersIdplayers;
	}

	@Column(name = "turns_history_players_has_quests_quests_idquests", nullable = false)
	public int getTurnsHistoryPlayersHasQuestsQuestsIdquests() {
		return this.turnsHistoryPlayersHasQuestsQuestsIdquests;
	}

	public void setTurnsHistoryPlayersHasQuestsQuestsIdquests(
			int turnsHistoryPlayersHasQuestsQuestsIdquests) {
		this.turnsHistoryPlayersHasQuestsQuestsIdquests = turnsHistoryPlayersHasQuestsQuestsIdquests;
	}

	@Column(name = "turns_history_places_has_transports_places_origin", nullable = false)
	public int getTurnsHistoryPlacesHasTransportsPlacesOrigin() {
		return this.turnsHistoryPlacesHasTransportsPlacesOrigin;
	}

	public void setTurnsHistoryPlacesHasTransportsPlacesOrigin(
			int turnsHistoryPlacesHasTransportsPlacesOrigin) {
		this.turnsHistoryPlacesHasTransportsPlacesOrigin = turnsHistoryPlacesHasTransportsPlacesOrigin;
	}

	@Column(name = "turns_history_places_has_transports_transportation", nullable = false)
	public int getTurnsHistoryPlacesHasTransportsTransportation() {
		return this.turnsHistoryPlacesHasTransportsTransportation;
	}

	public void setTurnsHistoryPlacesHasTransportsTransportation(
			int turnsHistoryPlacesHasTransportsTransportation) {
		this.turnsHistoryPlacesHasTransportsTransportation = turnsHistoryPlacesHasTransportsTransportation;
	}

	@Column(name = "turns_history_places_has_transports_places_destination", nullable = false)
	public int getTurnsHistoryPlacesHasTransportsPlacesDestination() {
		return this.turnsHistoryPlacesHasTransportsPlacesDestination;
	}

	public void setTurnsHistoryPlacesHasTransportsPlacesDestination(
			int turnsHistoryPlacesHasTransportsPlacesDestination) {
		this.turnsHistoryPlacesHasTransportsPlacesDestination = turnsHistoryPlacesHasTransportsPlacesDestination;
	}

	@Column(name = "placesrisks_idrisks", nullable = false)
	public int getPlacesrisksIdrisks() {
		return this.placesrisksIdrisks;
	}

	public void setPlacesrisksIdrisks(int placesrisksIdrisks) {
		this.placesrisksIdrisks = placesrisksIdrisks;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TurnsHistoryHasPlacesrisksId))
			return false;
		TurnsHistoryHasPlacesrisksId castOther = (TurnsHistoryHasPlacesrisksId) other;

		return (this.getTurnsHistoryPlayersHasQuestsPlayersIdplayers() == castOther
				.getTurnsHistoryPlayersHasQuestsPlayersIdplayers())
				&& (this.getTurnsHistoryPlayersHasQuestsQuestsIdquests() == castOther
						.getTurnsHistoryPlayersHasQuestsQuestsIdquests())
				&& (this.getTurnsHistoryPlacesHasTransportsPlacesOrigin() == castOther
						.getTurnsHistoryPlacesHasTransportsPlacesOrigin())
				&& (this.getTurnsHistoryPlacesHasTransportsTransportation() == castOther
						.getTurnsHistoryPlacesHasTransportsTransportation())
				&& (this.getTurnsHistoryPlacesHasTransportsPlacesDestination() == castOther
						.getTurnsHistoryPlacesHasTransportsPlacesDestination())
				&& (this.getPlacesrisksIdrisks() == castOther
						.getPlacesrisksIdrisks());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ this.getTurnsHistoryPlayersHasQuestsPlayersIdplayers();
		result = 37 * result
				+ this.getTurnsHistoryPlayersHasQuestsQuestsIdquests();
		result = 37 * result
				+ this.getTurnsHistoryPlacesHasTransportsPlacesOrigin();
		result = 37 * result
				+ this.getTurnsHistoryPlacesHasTransportsTransportation();
		result = 37 * result
				+ this.getTurnsHistoryPlacesHasTransportsPlacesDestination();
		result = 37 * result + this.getPlacesrisksIdrisks();
		return result;
	}

}
